// src/components/LocaleSwitcher.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';
import { MdTranslate } from 'react-icons/md';

export const LocaleSwitcher: React.FC = () => {
    const { i18n } = useTranslation();

    const switchLocale = (locale: string) => {
        i18n.changeLanguage(locale);
    };

    const localeName = (locale: string) => {
        const names: {[key: string]: string} = { "en": "English", "nl": "Nederlands" };
        return names[locale];
    };

    return (
        <div className="navbar-item has-dropdown is-hoverable">
            <a className="navbar-link">
                <span className="icon">
                    <MdTranslate />
                </span>
            </a>
            <div className="navbar-dropdown is-right">
                {['en', 'nl'].map(locale => (
                    <a
                        key={locale}
                        className="navbar-item"
                        onClick={() => switchLocale(locale)}
                    >
                        <span>{localeName(locale)}</span>
                    </a>
                ))}
            </div>
        </div>
    );
};

// version-with-working-buildings-but-no-map/src-old/components/LocaleSwitcher.vue
<template>
  <div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link">
      <b-icon icon="translate" />
    </a>
    <div
      class="navbar-dropdown is-right"
    >
      <a
        v-for="locale in $i18n.availableLocales"
        :key="locale"
        class="navbar-item"
        @click="switchLocale(locale)"
      >
        <span>{{ localeName(locale) }}</span>
      </a>
    </div>
  </div>
</template>

<script>

export default {

	name: "LocaleSwitcher",

	methods: {

		switchLocale( localeCode ) {

			this.$i18n.locale = localeCode;

		},
		localeName( locale ) {

			const localeNames = { "en": "English", "nl": "Nederlands" };

			return localeNames[ locale ];

		},

	}
};
</script>
